# =========================================================
# hexo-theme-sea 核心配置
# =========================================================


# 1. 导航菜单
menu:
  - name: 文章
    url: /posts/
  - name: 分类
    url: /categories/
  - name: 标签
    url: /tags/
  - name: 归档
    url: /archives/

# 2. 首页配置
home:
  hero:
    name: 愿景
    intro: 拒绝成为被生活“物理格式化”的零件。这里记录我读过的书、学过的技能，以及在这台复读机一样的人生里，强行插播的个人声音。如果不给生命留下点抓痕，潮水一涨，谁还记得我们来过？
    avatar: /blogs/images/avatar.png
  posts: recent

# 3. 外观设置
appearance:
  dark_mode: auto         # 自动跟随系统深色模式
  accent_color: "#2196f3" # 实验室主题色：海洋蓝

# 4. 社交链接
socialLink:
  - name: Github # 名称
    link: https://github.com/fe-sequoia # 跳转链接
  - name: Twitter # 名称
    link: https://github.com/fe-sequoia # 跳转链接
  - name: Facebook # 名称
    link: https://github.com/fe-sequoia # 跳转链接
  - name: Instagram # 名称
    link: https://github.com/fe-sequoia # 跳转链接

# 5. 评论设置 (如果你以后要用)
# valine:
#   enable: false
#   appId: 
#   appKey: 

# 6. 搜索 (Sea 通常内置简单搜索，无需额外复杂配置)
search:
  enable: true
  type: pagefind


favicon: /images/favicon.ico

# Footer
footer:
  builtUpTime: 2026-01-20 13:14:00 # 建站时间

# 主题色
primaryColor: '#10b981'
